/*
 * Copyright (c) 2016 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

package org.qeo.unittesttypes;

import org.qeo.Key;

/**
 * Basic device info published by any unregistered Qeo-enabled device.
 */
public class DE2602Data
{
    /**
     * The device identification generated by Qeo.
     */
    @Key
    public org.qeo.system.DeviceId deviceId;

    /**
     * The PEM-encoded public key generated by the device wanting a simplified registration (headless device).
     */
    @Key
    public String name;
}
