/*
 * Copyright (c) 2015 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockdeviceinfo_writer.h"

typedef struct _CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_factory_t* Expected_factory;

} CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE;

typedef struct _CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_factory_t* Expected_factory;

} CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE;

static struct Mockdeviceinfo_writerInstance
{
  int qeo_deviceinfo_publish_IgnoreBool;
  CMOCK_qeo_deviceinfo_publish_CALLBACK qeo_deviceinfo_publish_CallbackFunctionPointer;
  int qeo_deviceinfo_publish_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_deviceinfo_publish_CallInstance;
  int qeo_deviceinfo_destruct_IgnoreBool;
  CMOCK_qeo_deviceinfo_destruct_CALLBACK qeo_deviceinfo_destruct_CallbackFunctionPointer;
  int qeo_deviceinfo_destruct_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_deviceinfo_destruct_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockdeviceinfo_writer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_deviceinfo_publish_IgnoreBool)
    Mock.qeo_deviceinfo_publish_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_deviceinfo_publish_CallInstance, cmock_line, "Function 'qeo_deviceinfo_publish' called less times than expected.");
  if (Mock.qeo_deviceinfo_publish_CallbackFunctionPointer != NULL)
    Mock.qeo_deviceinfo_publish_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_deviceinfo_destruct_IgnoreBool)
    Mock.qeo_deviceinfo_destruct_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_deviceinfo_destruct_CallInstance, cmock_line, "Function 'qeo_deviceinfo_destruct' called less times than expected.");
  if (Mock.qeo_deviceinfo_destruct_CallbackFunctionPointer != NULL)
    Mock.qeo_deviceinfo_destruct_CallInstance = CMOCK_GUTS_NONE;
}

void Mockdeviceinfo_writer_Init(void)
{
  Mockdeviceinfo_writer_Destroy();
}

void Mockdeviceinfo_writer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_deviceinfo_publish_CallbackFunctionPointer = NULL;
  Mock.qeo_deviceinfo_publish_CallbackCalls = 0;
  Mock.qeo_deviceinfo_destruct_CallbackFunctionPointer = NULL;
  Mock.qeo_deviceinfo_destruct_CallbackCalls = 0;
}

void qeo_deviceinfo_publish(qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_deviceinfo_publish_CallInstance);
  Mock.qeo_deviceinfo_publish_CallInstance = CMock_Guts_MemNext(Mock.qeo_deviceinfo_publish_CallInstance);
  if (Mock.qeo_deviceinfo_publish_IgnoreBool)
  {
    return;
  }
  if (Mock.qeo_deviceinfo_publish_CallbackFunctionPointer != NULL)
  {
    Mock.qeo_deviceinfo_publish_CallbackFunctionPointer(factory, Mock.qeo_deviceinfo_publish_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_deviceinfo_publish' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeo_deviceinfo_publish' called with unexpected value for argument 'factory'.");
}

void CMockExpectParameters_qeo_deviceinfo_publish(CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = factory;
}

void qeo_deviceinfo_publish_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeo_deviceinfo_publish_IgnoreBool = (int)1;
}

void qeo_deviceinfo_publish_CMockExpect(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE));
  CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_deviceinfo_publish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_deviceinfo_publish_CallInstance = CMock_Guts_MemChain(Mock.qeo_deviceinfo_publish_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_deviceinfo_publish(cmock_call_instance, factory);
}

void qeo_deviceinfo_publish_StubWithCallback(CMOCK_qeo_deviceinfo_publish_CALLBACK Callback)
{
  Mock.qeo_deviceinfo_publish_CallbackFunctionPointer = Callback;
}

void qeo_deviceinfo_destruct(qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_deviceinfo_destruct_CallInstance);
  Mock.qeo_deviceinfo_destruct_CallInstance = CMock_Guts_MemNext(Mock.qeo_deviceinfo_destruct_CallInstance);
  if (Mock.qeo_deviceinfo_destruct_IgnoreBool)
  {
    return;
  }
  if (Mock.qeo_deviceinfo_destruct_CallbackFunctionPointer != NULL)
  {
    Mock.qeo_deviceinfo_destruct_CallbackFunctionPointer(factory, Mock.qeo_deviceinfo_destruct_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_deviceinfo_destruct' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeo_deviceinfo_destruct' called with unexpected value for argument 'factory'.");
}

void CMockExpectParameters_qeo_deviceinfo_destruct(CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = factory;
}

void qeo_deviceinfo_destruct_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeo_deviceinfo_destruct_IgnoreBool = (int)1;
}

void qeo_deviceinfo_destruct_CMockExpect(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE));
  CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_deviceinfo_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_deviceinfo_destruct_CallInstance = CMock_Guts_MemChain(Mock.qeo_deviceinfo_destruct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_deviceinfo_destruct(cmock_call_instance, factory);
}

void qeo_deviceinfo_destruct_StubWithCallback(CMOCK_qeo_deviceinfo_destruct_CALLBACK Callback)
{
  Mock.qeo_deviceinfo_destruct_CallbackFunctionPointer = Callback;
}

