/*
 * Copyright (c) 2015 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/**************************************************************
 ********          THIS IS A GENERATED FILE         ***********
 **************************************************************/

#import <Foundation/Foundation.h>
#import <Qeo/Qeo.h>
#import "qeo_types.h"


/**
 * The encrypted OTC (to be decrypted and used by the remote device) and the Security Management Server URL
 */
@interface org_qeo_system_RegistrationCredentials : QEOType

  /**
   * [Key]
   * The device identification generated by Qeo.
   */
  @property (strong,nonatomic) org_qeo_system_DeviceId * deviceId;
  /**
   * [Key]
   * The PEM-encoded public key generated by the remote device requesting a registration.
   */
  @property (strong,nonatomic) NSString * requestRSAPublicKey;
  /**
   * Array of NSNumber (int8_t)
   * The OTC (encrypted with the above public key using PKCS1 OEAP padding) to be used by the remote device
   */
  @property (strong,nonatomic) NSArray * encryptedOtc;
  /**
   * Security Management Server URL
   */
  @property (strong,nonatomic) NSString * url;
  /**
   * The name of the realm to use
   */
  @property (strong,nonatomic) NSString * realmName;

@end


