/*
 * Copyright (c) 2016 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/**************************************************************
 ********          THIS IS A GENERATED FILE         ***********
 **************************************************************/

#import <Foundation/Foundation.h>
#import <Qeo/Qeo.h>
#import "qeo_types.h"


/**
 * Basic device info published by any unregistered Qeo-enabled device.
 */
@interface org_qeo_system_RegistrationRequest : QEOType

  /**
   * [Key]
   * The device identification generated by Qeo.
   */
  @property (strong,nonatomic) org_qeo_system_DeviceId * deviceId;
  /**
   * [Key]
   * The PEM-encoded public key generated by the remote device requesting a registration.
   */
  @property (strong,nonatomic) NSString * rsaPublicKey;
  /**
   * [Key]
   * Version number indicating the encryption/padding algorithm supported.
   */
  @property (nonatomic) int16_t version;
  /**
   * [Key]
   * The manufacturer of the device (human readable string).
   */
  @property (strong,nonatomic) NSString * manufacturer;
  /**
   * [Key]
   * Model name of the device (human readable string).
   */
  @property (strong,nonatomic) NSString * modelName;
  /**
   * [Key]
   * Descriptive name of the device.
   */
  @property (strong,nonatomic) NSString * userFriendlyName;
  /**
   * [Key]
   * Suggested user name.
   */
  @property (strong,nonatomic) NSString * userName;
  /**
   * Registration status. Enumeration of the following states: UNREGISTERED, REGISTERING.
   */
  @property (nonatomic) int16_t registrationStatus;
  /**
   * Error code. Enumeration of the following errors: NONE, CANCELLED, REMOTE_REGISTRATION_TIMEOUT, PLATFORM_FAILURE, INVALID_OTP, INTERNAL_ERROR, NETWORK_FAILURE, SSL_HANDSHAKE_FAILURE, RECEIVED_INVALID_CREDENTIALS, STORE_FAILURE, UNKNOWN.
   */
  @property (nonatomic) int16_t errorCode;
  /**
   * Error message in case of registration failure.
   */
  @property (strong,nonatomic) NSString * errorMessage;

@end


