/*
 * Copyright (c) 2015 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/**************************************************************
 ********          THIS IS A GENERATED FILE         ***********
 **************************************************************/

#import <Foundation/Foundation.h>
#import <Qeo/Qeo.h>


/**
 * this is the device ID generated by Qeo.
 */
@interface org_qeo_system_DeviceId : QEOType

  /**
   * Upper 64-bit of identifier.
   */
  @property (nonatomic) int64_t upper;
  /**
   * Lower 64-bit of identifier.
   */
  @property (nonatomic) int64_t lower;

@end

/**
 * A generic 128-bit UUID.
 */
@interface org_qeo_UUID : QEOType

  /**
   * Upper 64-bit of identifier.
   */
  @property (nonatomic) int64_t upper;
  /**
   * Lower 64-bit of identifier.
   */
  @property (nonatomic) int64_t lower;

@end


