/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/**************************************************************
 ********          THIS IS A GENERATED FILE         ***********
 **************************************************************/

#ifndef QDM_MULTIPLEMODULES_H_
#define QDM_MULTIPLEMODULES_H_

#include <qeo/types.h>

#ifdef __cplusplus
extern "C"
{
#endif


/**
 * struct containing only primitive types
 */
typedef struct {
    qeo_boolean_t MyBoolean;
    int8_t MyByte;
    int16_t MyInt16;
    int32_t MyInt32;
    int64_t MyInt64;
    float MyFloat32;
    char * MyString;
} module_first_MyStructWithPrimitives_t;
extern const DDS_TypeSupport_meta module_first_MyStructWithPrimitives_type[];

DDS_SEQUENCE(module_first_MyStructWithPrimitives_t, module_first_Class1_MyUnbArrayOfStructWithPrimitives_seq);
/**
 * this is the device ID generated by Qeo.
 */
typedef struct {
    int64_t upper;
    module_first_Class1_MyUnbArrayOfStructWithPrimitives_seq MyUnbArrayOfStructWithPrimitives;
    int64_t lower;
} module_first_Class1_t;
extern const DDS_TypeSupport_meta module_first_Class1_type[];

/**
 * struct containing only primitive types
 */
typedef struct {
    qeo_boolean_t MyBoolean;
    int8_t MyByte;
    int16_t MyInt16;
    int32_t MyInt32;
    int64_t MyInt64;
    float MyFloat32;
    char * MyString;
} module_second_MyStructWithPrimitives_t;
extern const DDS_TypeSupport_meta module_second_MyStructWithPrimitives_type[];

/**
 * this is the device ID 2 generated by Qeo.
 */
typedef struct {
    int64_t upper2;
    int64_t lower2;
} module_second_Class1_t;
extern const DDS_TypeSupport_meta module_second_Class1_type[];

#ifdef __cplusplus
}
#endif

#endif /* QDM_MULTIPLEMODULES_H_ */

