/*
 * Copyright (c) 2015 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/**************************************************************
 ********          THIS IS A GENERATED FILE         ***********
 **************************************************************/

#import <Foundation/Foundation.h>
#import <Qeo/Qeo.h>

/**
 * struct containing only primitive types
 */
@interface module_first_MyStructWithPrimitives : QEOType

  @property (nonatomic) BOOL MyBoolean;
  @property (nonatomic) int8_t MyByte;
  @property (nonatomic) int16_t MyInt16;
  @property (nonatomic) int32_t MyInt32;
  @property (nonatomic) int64_t MyInt64;
  @property (nonatomic) float MyFloat32;
  @property (strong,nonatomic) NSString * MyString;

@end

/**
 * this is the device ID generated by Qeo.
 */
@interface module_first_Class1 : QEOType

  @property (nonatomic) int64_t upper;
  /**
   * Array of module_first_MyStructWithPrimitives
   */
  @property (strong,nonatomic) NSArray * MyUnbArrayOfStructWithPrimitives;
  @property (nonatomic) int64_t lower;

@end

/**
 * struct containing only primitive types
 */
@interface module_second_MyStructWithPrimitives : QEOType

  @property (nonatomic) BOOL MyBoolean;
  @property (nonatomic) int8_t MyByte;
  @property (nonatomic) int16_t MyInt16;
  @property (nonatomic) int32_t MyInt32;
  @property (nonatomic) int64_t MyInt64;
  @property (nonatomic) float MyFloat32;
  @property (strong,nonatomic) NSString * MyString;

@end

/**
 * this is the device ID 2 generated by Qeo.
 */
@interface module_second_Class1 : QEOType

  @property (nonatomic) int64_t upper2;
  @property (nonatomic) int64_t lower2;

@end


